name: Node.js CI

on:
    push:
        branches: ["develop"]

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: create env file
              run: |
                  touch .env
                  echo MONOGODBURL=${{ secrets.MONOGODBURL }} >> .env
                  echo PORT=${{ secrets.PORT }} >> .env
                  echo SECRET=${{ secrets.SECRET }} >> .env
                  echo PASSWORD=${{ secrets.PASSWORD }} >> .env
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - run: npm ci
            - run: pm2 restart server
